---
version: "2"
services:
    www:
        build: .
        image: haydevops/phpcompose:44
        ports:
            - 45678:80
       
        depends_on:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: ranjit
            MYSQL_PASSWORD: ranjit
            MYSQL_ROOT_PASSWORD: ranjit
       
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        
        links:
            - db:db
        ports:
            - 45679:80
        environment:
            MYSQL_USER: ranjit
            MYSQL_PASSWORD: ranjit
            MYSQL_ROOT_PASSWORD: ranjit
volumes:
    persistent:

