---
version: "2"
services:
    www:
        build: .
        tags:
            - haydevops/hayphp
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        tags:
            - haydevops/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: ranjit
            MYSQL_PASSWORD: ranjit
            MYSQL_ROOT_PASSWORD: ranjit
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        tags:
            - haydevops/hayphpadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: ranjit
            MYSQL_PASSWORD: ranjit
            MYSQL_ROOT_PASSWORD: ranjit
volumes:
    persistent:

