---
version: "2"
services:
    www:
        build: .
        image: haydevops/phpcompose:27
        ports:
            - "8087:8087"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: ranjit
            MYSQL_PASSWORD: ranjit
            MYSQL_ROOT_PASSWORD: ranjit
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        
        links:
            - db:db
        ports:
            - 8088:8088
        environment:
            MYSQL_USER: ranjit
            MYSQL_PASSWORD: ranjit
            MYSQL_ROOT_PASSWORD: ranjit
volumes:
    persistent:

